In [6]:
import pandas as pd
import numpy as np

In [7]:
labels=["Baral","Prashant","ram"]
labels

['Baral', 'Prashant', 'ram']

In [8]:
arr=np.array([1,2,3,4,5])
d={"prashant":3,"Wagle":4,"Ram":5}

In [9]:
pd.Series(d)

prashant    3
Wagle       4
Ram         5
dtype: int64

In [10]:
my_list=np.arange(3)
my_list

array([0, 1, 2])

In [11]:
ser1=pd.Series(data=my_list ,index=labels)
ser1

Baral       0
Prashant    1
ram         2
dtype: int32

In [12]:
ser2=pd.Series([1,2,3],index=["Prashant","Baral","Wagle"])
ser2

Prashant    1
Baral       2
Wagle       3
dtype: int64

In [13]:
ser1+ser2

Baral       2.0
Prashant    2.0
Wagle       NaN
ram         NaN
dtype: float64

In [14]:
ser1.add(ser2) #add the value of matching index if not return Nan

Baral       2.0
Prashant    2.0
Wagle       NaN
ram         NaN
dtype: float64

In [15]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [16]:
df=pd.DataFrame(np.random.randn(5,4),index=("A","B","C","D","E"),columns=("W","X","Y","Z"))
df

W         X         Y         Z
A -0.671318 -1.551910  0.102442  1.611443
B  1.298080  0.266689  0.278762  1.689563
C -0.001093  1.579382 -0.586478  0.990532
D -0.391343  0.244064  0.351868  0.272569
E -2.556949 -0.784091 -1.719963 -0.084061

In [17]:
type(df["W"])

pandas.core.series.Series

In [18]:
type(df)

pandas.core.frame.DataFrame

In [19]:
df["W"]

A   -0.671318
B    1.298080
C   -0.001093
D   -0.391343
E   -2.556949
Name: W, dtype: float64

In [20]:
df.loc["D"]

W   -0.391343
X    0.244064
Y    0.351868
Z    0.272569
Name: D, dtype: float64

In [21]:
df.iloc[3]

W   -0.391343
X    0.244064
Y    0.351868
Z    0.272569
Name: D, dtype: float64

In [22]:
df.iloc[[2,4],1]

C    1.579382
E   -0.784091
Name: X, dtype: float64

In [23]:
df.iloc[[2,3,4],[1,2,3]]

X         Y         Z
C  1.579382 -0.586478  0.990532
D  0.244064  0.351868  0.272569
E -0.784091 -1.719963 -0.084061

In [24]:
df.loc[["C","D","E"],["X","Y","Z"]]

X         Y         Z
C  1.579382 -0.586478  0.990532
D  0.244064  0.351868  0.272569
E -0.784091 -1.719963 -0.084061

In [25]:
df.iloc[2:4,1:3]

X         Y
C  1.579382 -0.586478
D  0.244064  0.351868

In [26]:
df>0

W      X      Y      Z
A  False  False   True   True
B   True   True   True   True
C  False   True  False   True
D  False   True   True   True
E  False  False  False  False

In [27]:
df[df>0]

W         X         Y         Z
A      NaN       NaN  0.102442  1.611443
B  1.29808  0.266689  0.278762  1.689563
C      NaN  1.579382       NaN  0.990532
D      NaN  0.244064  0.351868  0.272569
E      NaN       NaN       NaN       NaN

In [28]:
df[df["X"]>0]["Y"] #if x is >0 print the corresponding value of y

B    0.278762
C   -0.586478
D    0.351868
Name: Y, dtype: float64

In [29]:
df=pd.DataFrame({"CE":[1,2,3],"Electrical":[1,2,3],"Pharm":[np.nan,3,4]},index=("C++", "Math", "Electrical"))
df

CE  Electrical  Pharm
C++          1           1    NaN
Math         2           2    3.0
Electrical   3           3    4.0

In [30]:
df.dropna()

CE  Electrical  Pharm
Math         2           2    3.0
Electrical   3           3    4.0

In [31]:
df.dropna(axis=0)

CE  Electrical  Pharm
Math         2           2    3.0
Electrical   3           3    4.0

In [32]:
df.dropna(axis=1)

CE  Electrical
C++          1           1
Math         2           2
Electrical   3           3

In [33]:
df.fillna(value="data Missing")

CE  Electrical         Pharm
C++          1           1  data Missing
Math         2           2           3.0
Electrical   3           3           4.0

In [34]:
df["Pharm"].fillna(value=df["Pharm"].mean())

C++           3.5
Math          3.0
Electrical    4.0
Name: Pharm, dtype: float64

In [35]:
df["Pharm"]=df["Pharm"].fillna(value=df["Pharm"].mean())

In [36]:
df

CE  Electrical  Pharm
C++          1           1    3.5
Math         2           2    3.0
Electrical   3           3    4.0

In [37]:
df["Pharm"].fillna(value=df["Pharm"].mean(),inplace=True) #same as df["Pharm"]=df["Pharm"].fillna(value=df["Pharm"].mean())

In [38]:
df

CE  Electrical  Pharm
C++          1           1    3.5
Math         2           2    3.0
Electrical   3           3    4.0

In [39]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}


In [40]:
df=pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [41]:
df["Company"].unique()

array(['GOOG', 'MSFT', 'FB'], dtype=object)

In [42]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [43]:
data={'subject':['C++','DBMS','MCSC','MATH'],'instructor':['Rajani','Santosh','Gokul','Saraswoti'],'Assignment':[10,12,4,7]}  

In [44]:
df=pd.DataFrame(data)
df

subject instructor  Assignment
0     C++     Rajani          10
1    DBMS    Santosh          12
2    MCSC      Gokul           4
3    MATH  Saraswoti           7

In [45]:
df.set_index("subject",inplace=True)

In [46]:
df.set_index("Assignment",inplace=True)
df

instructor
Assignment           
10             Rajani
12            Santosh
4               Gokul
7           Saraswoti

In [47]:
df

instructor
Assignment           
10             Rajani
12            Santosh
4               Gokul
7           Saraswoti

In [48]:
df.reset_index("subject",inplace=True)
df

KeyError: 'Requested level (subject) does not match index name (Assignment)'

In [ ]:
df["Assignment"].value_counts()

Assignment
10    1
12    1
4     1
7     1
Name: count, dtype: int64

In [ ]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
def times(x):
    return x*3

df.apply(times)

subject                   instructor
Assignment                                           
10             C++C++C++           RajaniRajaniRajani
12          DBMSDBMSDBMS        SantoshSantoshSantosh
4           MCSCMCSCMCSC              GokulGokulGokul
7           MATHMATHMATH  SaraswotiSaraswotiSaraswoti

In [ ]:
np.arange?

Object `np.arange` not found.


In [50]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[]